//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Core.Entites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolSystemEntities : DbContext
    {
        public SchoolSystemEntities()
            : base("name=SchoolSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ismail_Classes> Ismail_Classes { get; set; }
        public virtual DbSet<Ismail_Clients> Ismail_Clients { get; set; }
        public virtual DbSet<Ismail_ErrorLogs> Ismail_ErrorLogs { get; set; }
        public virtual DbSet<Ismail_Gender> Ismail_Gender { get; set; }
        public virtual DbSet<Ismail_Languages> Ismail_Languages { get; set; }
        public virtual DbSet<Ismail_StudentMarks> Ismail_StudentMarks { get; set; }
        public virtual DbSet<Ismail_TranslationCientLanguage> Ismail_TranslationCientLanguage { get; set; }
        public virtual DbSet<Ismail_Types> Ismail_Types { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<Ismail_AssociationDynamic_Result> Ismail_AssociationDynamic(Nullable<int> adminUserID, string operationType, Nullable<int> clientID, Nullable<int> classID, Nullable<int> newClassID)
        {
            var adminUserIDParameter = adminUserID.HasValue ?
                new ObjectParameter("AdminUserID", adminUserID) :
                new ObjectParameter("AdminUserID", typeof(int));
    
            var operationTypeParameter = operationType != null ?
                new ObjectParameter("OperationType", operationType) :
                new ObjectParameter("OperationType", typeof(string));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            var newClassIDParameter = newClassID.HasValue ?
                new ObjectParameter("NewClassID", newClassID) :
                new ObjectParameter("NewClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ismail_AssociationDynamic_Result>("Ismail_AssociationDynamic", adminUserIDParameter, operationTypeParameter, clientIDParameter, classIDParameter, newClassIDParameter);
        }
    }
}
