//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Core.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ismail_Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ismail_Clients()
        {
            this.Ismail_TranslationCientLanguage = new HashSet<Ismail_TranslationCientLanguage>();
            this.Ismail_Classes = new HashSet<Ismail_Classes>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public int GenderID { get; set; }
        public int TypeID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual Ismail_Gender Ismail_Gender { get; set; }
        public virtual Ismail_StudentMarks Ismail_StudentMarks { get; set; }
        public virtual Ismail_Types Ismail_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ismail_TranslationCientLanguage> Ismail_TranslationCientLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ismail_Classes> Ismail_Classes { get; set; }
    }
}
