//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Core.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ismail_Gender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ismail_Gender()
        {
            this.Ismail_Clients = new HashSet<Ismail_Clients>();
        }
    
        public int GenderID { get; set; }
        public string GenderDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ismail_Clients> Ismail_Clients { get; set; }
    }
}
