//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Core.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ismail_Languages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ismail_Languages()
        {
            this.Ismail_TranslationCientLanguage = new HashSet<Ismail_TranslationCientLanguage>();
        }
    
        public int LanguageID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ismail_TranslationCientLanguage> Ismail_TranslationCientLanguage { get; set; }
    }
}
