//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Core.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ismail_TranslationCientLanguage
    {
        public int LanguageID { get; set; }
        public int UserID { get; set; }
        public string DisplayName { get; set; }
    
        public virtual Ismail_Clients Ismail_Clients { get; set; }
        public virtual Ismail_Languages Ismail_Languages { get; set; }
    }
}
