//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Core.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ismail_ErrorLogs
    {
        public int ErrorId { get; set; }
        public string ErrorCode { get; set; }
        public string UserMessage { get; set; }
        public string TechnicalMessage { get; set; }
        public string StackTraces { get; set; }
        public string Source { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsResolve { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
        public string ResolutionNote { get; set; }
    }
}
