//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Core.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ismail_StudentMarks
    {
        public int StudentID { get; set; }
        public int Physics { get; set; }
        public int Math { get; set; }
        public int Chemistry { get; set; }
        public int English { get; set; }
    
        public virtual Ismail_Clients Ismail_Clients { get; set; }
    }
}
